<a href="https://colab.research.google.com/github/EfeBastug/learning-deep-learning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


In [2]:
print("Hello again")

Hello again


In [3]:
print("First push denemesi")

First push denemesi


In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [5]:
import torch
print(torch.__version__)

2.9.0+cpu


In [7]:
import pandas as pd

In [8]:
import pandas as pd

In [9]:
##Introduction to Tensors

Introduction To Tensors

Creating tensors

In [10]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [12]:
scalar.item()

7

In [13]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [16]:
#MATRIX
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
matrix.ndim

2

In [18]:
matrix[0]
matrix[1]
matrix.shape

torch.Size([2, 2])

In [19]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [20]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [25]:
tensor_3_3_3 = torch.rand(3, 3, 3)
tensor_3_3_3

tensor([[[0.2554, 0.9934, 0.7481],
         [0.4770, 0.6999, 0.1447],
         [0.9093, 0.7123, 0.6593]],

        [[0.0348, 0.5011, 0.5021],
         [0.9162, 0.8107, 0.5338],
         [0.5048, 0.1592, 0.9580]],

        [[0.3739, 0.5250, 0.0679],
         [0.6664, 0.0217, 0.4151],
         [0.6660, 0.5977, 0.9778]]])

In [26]:
tensor_3_3_3.shape

torch.Size([3, 3, 3])

In [27]:
tensor_3_3_3[0]

tensor([[0.2554, 0.9934, 0.7481],
        [0.4770, 0.6999, 0.1447],
        [0.9093, 0.7123, 0.6593]])

Random tensors

Most random tensors start with random numbers -> look at data -> update random numbers -> look at data

In [30]:
#Create a random tensor of size (3,5)
rand_tensor = torch.rand(10, 10, 10)
rand_tensor

tensor([[[0.2475, 0.8018, 0.6709, 0.1935, 0.4744, 0.7747, 0.2665, 0.2848,
          0.4249, 0.6189],
         [0.7489, 0.3596, 0.8372, 0.1040, 0.9252, 0.1774, 0.1231, 0.5081,
          0.7286, 0.3545],
         [0.2842, 0.6155, 0.4171, 0.5995, 0.8879, 0.8712, 0.6328, 0.8694,
          0.1336, 0.7968],
         [0.8277, 0.0021, 0.3185, 0.4501, 0.0295, 0.9310, 0.9095, 0.1075,
          0.7251, 0.8691],
         [0.5147, 0.7067, 0.8650, 0.9201, 0.0988, 0.2505, 0.4315, 0.9774,
          0.6319, 0.0044],
         [0.9369, 0.7915, 0.8182, 0.8446, 0.5325, 0.3497, 0.9818, 0.6504,
          0.8271, 0.2517],
         [0.0972, 0.8837, 0.1261, 0.4095, 0.3420, 0.5406, 0.9283, 0.7912,
          0.4503, 0.3703],
         [0.7000, 0.7727, 0.6711, 0.6630, 0.0114, 0.4760, 0.6152, 0.1894,
          0.5180, 0.8020],
         [0.9851, 0.3114, 0.6380, 0.1762, 0.3913, 0.9194, 0.5342, 0.9444,
          0.2586, 0.7524],
         [0.5853, 0.4957, 0.9594, 0.6051, 0.2317, 0.1347, 0.5327, 0.1857,
          0.5554,

In [29]:
rand_tensor.ndim

2

In [31]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width and color
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [32]:
#Create a random tensor of 67, 67, 67
tensor67 = torch.rand(67, 67, 67)

In [33]:
tensor67

tensor([[[0.5187, 0.9393, 0.4481,  ..., 0.1061, 0.1449, 0.3650],
         [0.9220, 0.0551, 0.0847,  ..., 0.7483, 0.8790, 0.8097],
         [0.8161, 0.0984, 0.2932,  ..., 0.0266, 0.9830, 0.1358],
         ...,
         [0.3565, 0.8134, 0.8523,  ..., 0.9018, 0.5608, 0.6906],
         [0.8412, 0.1673, 0.5325,  ..., 0.1264, 0.6369, 0.9722],
         [0.1756, 0.7964, 0.7378,  ..., 0.8280, 0.6035, 0.6558]],

        [[0.4438, 0.6133, 0.5926,  ..., 0.2132, 0.2081, 0.4126],
         [0.7748, 0.9734, 0.3180,  ..., 0.3101, 0.5997, 0.5793],
         [0.3478, 0.8828, 0.1935,  ..., 0.8529, 0.6820, 0.2116],
         ...,
         [0.9832, 0.9376, 0.2016,  ..., 0.9503, 0.0266, 0.4745],
         [0.6326, 0.5087, 0.9019,  ..., 0.3001, 0.8267, 0.1743],
         [0.7253, 0.7776, 0.0404,  ..., 0.9513, 0.8266, 0.5687]],

        [[0.2537, 0.4692, 0.6900,  ..., 0.0320, 0.1301, 0.5456],
         [0.0748, 0.6742, 0.9800,  ..., 0.6355, 0.2163, 0.9081],
         [0.6463, 0.8669, 0.9910,  ..., 0.7453, 0.3956, 0.

In [34]:
#Zeros tensor
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
ones.dtype

torch.float32

In [37]:
scalar.dtype

torch.int64

In [38]:
#Use torch.range()
torch.range(0, 10)

/tmp/ipython-input-3660775452.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
one_to_ten = torch.arange(start=0, end=110, step=10)
one_to_ten

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [42]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])